project: 
  type: website
  
website: 
  page-navigation: true
  title: "NMFS Bioinformatics Resources" 
  site-url: "https://nmfs-ost.github.io/Genomics_Resources/" 
  repo-url: https://github.com/nmfs-ost/Genomics_Resources
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    
  sidebar:
    logo: "images/openscapes_hex.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/nmfs-ost/Genomics_Resources
        text: "NMFS Genomics Resources github"   

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - explore.qmd
      - section: quarto-workflows/index.qmd
        contents: 
          - quarto-workflows/browser.md
          - quarto-workflows/rstudio.qmd
          - quarto-workflows/jupyter.md 
      - learning-more.qmd
      - href: transition-from-rmarkdown.qmd
        text: Transition from Rmd


format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
