project: 
  type: website
  
website: 
  page-navigation: true
  title: "NMFS Bioinformatics Resources" 
  site-url: "https://nmfs-ost.github.io/Genomics_Resources/" 
  repo-url: https://github.com/nmfs-ost/Genomics_Resources
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    
  sidebar:
    logo: "images/logo_tmp.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/nmfs-ost/Genomics_Resources
        text: "NMFS Genomics Resources github"   

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - href: workshops.qmd
        text: Workshops
      - href: computing.qmd
        text: HPC

format:
  html:
    theme: flatly
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
